version: "3.4"

x-app: &default-app
  build:
    context: "leaktopus_backend/."
    target: "app"
    args:
      - "FLASK_ENV=${FLASK_ENV:-production}"
  depends_on:
    - redis
  env_file:
    - ".env"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  volumes:
    - "./leaktopus_backend/db/:/db"
    - "./leaktopus_backend/:/app"
#    - "./leaktopus_backend/private-key.pem:/app/private-key.pem"

services:
  redis:
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_REDIS_CPUS:-0}"
          memory: "${DOCKER_REDIS_MEMORY:-0}"
    env_file:
      - ".env"
    image: "redis:6.0.10-buster"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"

  web:
    <<: *default-app
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:8000/up}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - "${DOCKER_WEB_PORT_FORWARD:-localhost:8000}:8000"

  frontend:
    build: "./leaktopus_frontend"
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    env_file:
      - ".env"
    ports:
      - "8080:80"

  worker:
    <<: *default-app
    entrypoint: watchmedo auto-restart --directory=./leaktopus/ --patterns=*.py --recursive -- celery -A "leaktopus.celery_app.celery" worker --beat -s ${CELERY_FILES_PATH}/celerybeat-schedule -l "${CELERY_LOG_LEVEL:-info}"
#    depends_on:
#      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WORKER_CPUS:-0}"
          memory: "${DOCKER_WORKER_MEMORY:-0}"
    volumes:
      - ./leaktopus_backend/data/:/data
      - ./leaktopus_backend/db/:/db
      - ./leaktopus_backend/:/app
      - /var/run/docker.sock:/var/run/docker.sock

#  elasticsearch:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    volumes:
#      - type: bind
#        source: ./elasticsearch/config/elasticsearch.yml
#        target: /usr/share/elasticsearch/config/elasticsearch.yml
#        read_only: true
#      - type: volume
#        source: elasticsearch
#        target: /usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#      ELASTIC_PASSWORD: $ES_PASS
#      # Use single node discovery in order to disable production mode and avoid bootstrap checks
#      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#      discovery.type: single-node

#  logstash:
#    build:
#      context: logstash/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    volumes:
#      - type: bind
#        source: ./logstash/config/logstash.yml
#        target: /usr/share/logstash/config/logstash.yml
#        read_only: true
#      - type: bind
#        source: ./logstash/pipeline
#        target: /usr/share/logstash/pipeline
#        read_only: true
#    ports:
#      - "5000:5000/tcp"
#      - "5000:5000/udp"
#      - "9600:9600"
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#      ES_HOST: $ES_HOST
#      ES_PORT: $ES_PORT
#      ES_USER: $ES_USER
#      ES_PASS: $ES_PASS
#    depends_on:
#      - elasticsearch

#  kibana:
#    build:
#      context: kibana/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    environment:
#      ES_HOST: $ES_HOST
#      ES_PORT: $ES_PORT
#      ES_USER: $ES_USER
#      ES_PASS: $ES_PASS
#    volumes:
#      - type: bind
#        source: ./kibana/config/kibana.yml
#        target: /usr/share/kibana/config/kibana.yml
#        read_only: true
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch

volumes:
  db: {}
  data: {}
  redis: {}
#  elasticsearch: {}
