#!/usr/bin/env bash

mkdir -p commits_data

shas=$(git rev-list HEAD)
for sha1 in $shas; do
    git show --ignore-cr-at-eol --ignore-space-at-eol -w -b --ignore-blank-lines --no-prefix --ignore-submodules --no-indent-heuristic --cc --format='' $sha1 > ./commits_data/$sha1
done
